image:
  file: .devcontainer/gitpod.Dockerfile

tasks:
  - init: yarn install

vscode:
  extensions:
    # base extensions, TODO: abstract
    # I think we can install them in the base image?
    - coenraads.bracket-pair-colorizer-2
    # language-specific
    - flowtype.flow-for-vscode
    - dbaeumer.vscode-eslint
